### ISSUE TITLE
typo in readme

### ISSUE THREAD

**Issue by blindgaenger** [frzi/Model3DView-Examples#1]
Hi there, 

I just wanted to say that you have a typo in the url. Would be a shame if people couldn't find your new stuff. 

https://github.com/frzi/Model3DView-Examples/blob/f38618b79b96310ee4c3bc202f7c00fd2a4a75b5/README.md?plain=1#L8

Cheers!

**Comment by frzi** [comment]
Haha embarrassing. Thank you so much! 😄
